apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: byebye-world
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ashu-9/argo03
    targetRevision: master
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
