apiVersion: apps/v1
kind: Deployment
metadata:
  name: byebye-world
  labels:
    app: byebye-world
    org: orange
spec:
  replicas: 4
  selector:
    matchLabels:
      app: byebye-world
  template:
    metadata:
      labels:
        app: byebye-world
    spec:
      containers:
      - name: byebye-world
        image: ashu9/byebye-world:latest
        ports:
        - containerPort: 5000
